rm(list = ls())
gc()
require(data.table)
require(cowplot)
fuck <- fread('stat_final.txt')
fuck <- data.table(table(fuck[,1]), cumsum(table(fuck[,1])))
setnames(fuck, c('Occurrency', 'gene number', 'cumsum number'))
fuck <- melt(fuck, id = 1, variable.name = "Type")
ggplot() + geom_bar(data = fuck, aes(x = Occurrency, y = value, fill = Type), position = 'identity', stat = 'identity', alpha = 0.3) + scale_y_log10(expand = c(0.01, 0)) + scale_fill_manual(values = c('black', '#666666')) + labs(y = 'Gene number')