#' Tittle Kegg annotation comparison of signature genes 
#' @param crossOB a summary.crossICC object 
#' @param annoteDB annotationDB
#' @param idtype should be on of types in  `keytypes(org.Hs.eg.db)`
#' @import clusterProfiler
#' @import 
#' @return a annotation matrix generated by cluster profile 
#' @export
#'
#'

library(org.Hs.eg.db)
library(clusterProfiler)
anno.signatureKEGG <- function(crossOB,idtype) {
  convert_fun<-function(x){
   df<- bitr(x, fromType=idtype, toType=c( "ENTREZID"), OrgDb="org.Hs.eg.db")
    return(df[,2])
  }
  
  sum.crossOB.signatures<-summary.CrossICC(crossOB)$gene.signatures
  sum.crossOB.signatures$Genes<-stringi::stri_split(sum.crossOB.signatures$Genes,regex = "\\.",simplify=T)[,1]
  ID.list<-tapply(sum.crossOB.signatures$Genes, sum.crossOB.signatures$Cluster, convert_fun)
  ID.list<-lapply(ID.list,function(x){return(x)})
  ck <- compareCluster(geneCluster = ID.list, fun = "enrichKEGG")
  return(ck)
}

plot
obj<-readRDS("scriptsWithData/TCGAdataAnalysisFunctions/CrossICC.object.rds")

ck<-anno.signatureKEGG(obj,idtype = "ENSEMBL")
