rm(list = ls())
gc()
require(data.table)
require(cowplot)
met <- fread('tumor_vs_met/metasis_TCGA.maf')
tum <- fread('tumor_vs_met/tumor_TCGA.maf')
tum.VS.met <- data.table(tum$Tumor_Sample_Barcode, tum$ChromChange %in% met$ChromChange, tum$Hugo_Symbol)
met.VS.tum <- data.table(met$Tumor_Sample_Barcode, met$ChromChange %in% tum$ChromChange, met$Hugo_Symbol)
fuck <- unique(as.vector(as.matrix(met.VS.tum[,1], tum.VS.met[,1])))
Initial <- sapply(fuck, function(x) table(tum.VS.met[V1 == x])[1])
Common <- sapply(fuck, function(x) unique(table(met.VS.tum[V1 == x])[2], table(tum.VS.met[V1 == x])[2]))
Recurrence <- sapply(fuck, function(x) table(met.VS.tum[V1 == x])[1])
mutations <- data.table(Initial = Initial, Common = Common, Recurrence = Recurrence, Samples = fuck)
rm(Initial, Common, Recurrence, fuck)
mutations <- melt(mutations, id = 'Samples', variable.name = 'Types')
mbar <- ggplot() + geom_col(data = mutations, aes(x = Samples, y = value, fill = Types)) + ylab('Somantic mutations')
met.VS.tum[, V2 := as.character(V2)][V2 == 'FALSE', V2 := "Only recurrence"][V2 == 'TRUE', V2 := "Common"]
tum.VS.met[, V2 := as.character(V2)][V2 == 'FALSE', V2 := "Only inital"][V2 == 'TRUE', V2 := "Common"]
mutations <- rbind(met.VS.tum, tum.VS.met)
names(mutations) <- c("Samples", "Types", "Genes")
mheatmap <- ggplot() + geom_tile(data = mutations, aes(x = Samples, y = Genes, fill = Types), width = 0.7, height = 0.7, colour = 'black', size = 1)
ggdraw() + draw_plot(mbar, 0, 0.5, 1, 0.5) + draw_plot(mheatmap, 0, 0, 1, 0.5) + draw_plot_label(c("a", "b"), c(0, 0), c(1, .5), size = 15)
